Add CC to SendEmail
StackStorm-Exchange/stackstorm-email pull request #24
Opened 2019-07-12 16:28 UTC by rdjogo

I added the CC field because a specific use case requested it (create tasks on Asana via email, and add watchers via CC as per Asana documentation).

2019-07-12 16:55 UTC, jinpingh approved these changes
LGTM

2019-07-13 20:14 UTC, blag requested changes

2019-07-13 20:14 UTC, blag commented on actions/send_email.py
> +    def run(self, email_from, email_to, subject, message, account, email_cc=[], mime="plain", attachments=None):
This doesn't do what you think it does, and it introduces a very frustrating subtle bug.

See this [Stack Overflow post](https://stackoverflow.com/questions/366422/what-is-the-pythonic-way-to-avoid-default-parameters-that-are-empty-lists) for more about it, and how to fix it.

2019-07-13 20:23 UTC, rdjogo commented on actions/send_email.py
> +    def run(self, email_from, email_to, subject, message, account, email_cc=[], mime="plain", attachments=None):
Thanks, will do!

2019-07-13 20:36 UTC, rdjogo commented on actions/send_email.py
> +    def run(self, email_from, email_to, subject, message, account, email_cc=[], mime="plain", attachments=None):
Better now?

2019-07-13 22:12 UTC, blag approved these changes
:+1:

2019-07-15 20:38 UTC, punkrokk commented
would it make sense to add the same for BCC at this time, since that could also be a use case?

2019-07-16 16:58 UTC, blag commented
Properly supporting BCC headers can only be done after (or as part of) fixing #25.

2019-07-17 10:05 UTC, rdjogo commented
@blag I'll try and give #25 a go.

2019-07-20 08:21 UTC, merged